<a href="https://colab.research.google.com/github/ferdanischool-pixel/pemrograman-dasar/blob/main/ATS_Praktikum_Kelompok_8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

###**Kelompok 8**

1. **Ferdani**              **4232401043**
2. **Rizki Hakim Kumorow**  **4232401050**
3. **Putri Maulani**        **4232401046**

In [5]:
# 1. Percabangan / Branching
## 🌡️ Percabangan Suhu Air Pendingin


try:
    suhu = float(input("Masukkan suhu air pendingin (°C): "))
    if suhu <= 90.0:
        print("STATUS: Normal")
    elif suhu < 100.0:
        print("STATUS: Warning")
    else:
        print("ALERT: SHUTDOWN")

except ValueError:
    print("Input tidak valid. Harap masukkan angka untuk suhu.")

Masukkan suhu air pendingin (°C): 95
STATUS: Warning


PENJELASAN :
Program ini dibuat untuk mengklasifikasikan status operasional suatu sistem berdasarkan suhu air pendingin yang diukur oleh sensor. Masalah yang diselesaikan oleh program ini adalah menentukan status kritis sistem (Normal, Warning, atau SHUTDOWN) berdasarkan satu data input sensor suhu.
Cara kerja program ini berfokus pada menerima input dari pengguna dan menerapkan logika perbandingan berjenjang (if-elif-else) untuk menghasilkan status yang sesuai.
1. try : Memulai blok penanganan kesalahan (error handling). Kode di dalamnya akan dijalankan, dan jika terjadi kesalahan (ValueError), program tidak akan crash tetapi melompat ke blok except.
2. suhu = float(input("Masukkan suhu air pendingin (°C): ")) : Baris ini meminta input dari pengguna dan mencoba mengonversinya menjadi tipe data float (angka desimal). Ini menyelesaikan poin A.
3. if suhu <= 90.0: : Awal dari blok percabangan (branching). Ini adalah kondisi pertama yang dicek. Jika benar, program mencetak "STATUS: Normal" (Poin B).
4. print("STATUS: Normal") : jika pengguna memasukkan angka 90 atau lebih kecil (poin b) maka output akan Normal.
5.  elif suhu < 100.0 :   Ini adalah kondisi kedua. Ia HANYA diperiksa jika kondisi if sebelumnya  <= 90.0 salah (yaitu, suhu > 90.0). Jika benar, program mencetak "STATUS: Warning" (Poin C). Ini secara efektif mencakup rentang 90.0 < suhu < 100.0.
6. print("STATUS: Warning") : jika poin b salah maka dia akan mengecek poin c, jika bener maka output akan berstatus Warning.
7.  else: : Ini adalah kondisi default. Ia dieksekusi HANYA jika semua kondisi if dan elif di atasnya gagal. Dalam konteks ini,berarti suhu > 100.0. Jika dieksekusi, program mencetak "ALERT: SHUTDOWN" (Poin D).
8. except ValueError: : Menangkap kesalahan yang terjadi jika pengguna tidak memasukkan angka (misalnya, memasukkan teks). Jika ditangkap, program mencetak pesan kesalahan yang ramah.
9. print("Input tidak valid. Harap masukkan angka untuk suhu.") : jika pengguna memasukkan huruf maka print ini keluar di output.


In [8]:
# soal no 3 Data hasil pembacaan vibrasi dari 5 unit mesin

vibrasi_mesin = [1.2, 0.9, 2.5, 3.1, 1.8]
for i in range(len(vibrasi_mesin)):
    if vibrasi_mesin[i] > 2.0:
        print(f"Warning: Unit {i+1} vibrasi tinggi!")


**Penjelasan:**

1. vibrasi_mesin : list berisi data vibrasi dari 5 unit mesin.

2. for i in range(len(vibrasi_mesin)) : untuk melakukan perulangan sebanyak jumlah unit (5 kali).

3. if vibrasi_mesin[i] > 2.0 : memeriksa apakah nilai vibrasi melebihi batas aman 2.0.

4. print(f"Warning: Unit {i+1} vibrasi tinggi!") : menampilkan peringatan dengan nomor unit yang sesuai.

In [9]:
# soal no 5 menaikkan suhu 60°C hingga mencapai 85°C dengan menaikkan suhu sebesar 5°C tiap iterasi

suhu_saat_ini = 60
while suhu_saat_ini < 85:
    print(f"Suhu saat ini: {suhu_saat_ini}°C")
    suhu_saat_ini += 5
print("Suhu target 85°C tercapai.")


Suhu saat ini: 60°C
Suhu saat ini: 65°C
Suhu saat ini: 70°C
Suhu saat ini: 75°C
Suhu saat ini: 80°C
Suhu target 85°C tercapai.


**Penjelasan:**

1. suhu_saat_ini = 60 : titik awal suhu.

2. while suhu_saat_ini < 85: : perulangan terus berjalan selama suhu masih di bawah 85°C.

3. print(...) : menampilkan suhu setiap kali loop berjalan.

4. suhu_saat_ini += 5 : menaikkan suhu sebesar 5°C tiap iterasi.

5. Ketika suhu mencapai atau melebihi 85°C, loop berhenti, dan program mencetak pesan bahwa target tercapai.

In [10]:
# soal no 7 Mengklasifikasi Beban Listrik

kapasitas_maksimum_listrik = float(input("Masukkan kapasitas maksimum (Watt): "))
beban_listrik_terpakai = float(input("Masukkan beban terpakai (Watt): "))

persentase = (beban_listrik_terpakai / kapasitas_maksimum_listrik) * 100

if persentase <= 60:
    status = "Beban Ringan"
elif persentase <= 85:
    status = "Beban Sedang"
else:
    status = "Beban Berat"

print(f"\nPersentase Pemakaian Listrik: {persentase:.2f}%")
print(f"Status Beban: {status}")


Masukkan kapasitas maksimum (Watt): 2200
Masukkan beban terpakai (Watt): 1500

Persentase Pemakaian Listrik: 68.18%
Status Beban: Beban Sedang


**Penjelasan:**
1. Kode kapasitas_maksimum_listrik dan Kode beban_listrik_terpakai
adalah Input dari pengguna untuk menentukan kapasitas dan beban yang sedang digunakan.

2. Kode kapasitas_maksimum_listrik = 1200
adalah menunjukkan bahwa kapasitas maksimum beban listrik yang tersedia adalah 1200 Watt.

3. Kode beban_listrik_terpakai = 800
adalah menunjukkan bahwa daya listrik yang sedang digunakan adalah 800 Watt.

4. persentase = (beban_listrik_terpakai 800 Watt / kapasitas_maksimum_listrik 1200 Watt) * 100
akan menghitung persentase pemakaian daya terhadap kapasitas maksimum.

5. Fungsi if digunakan pada persentase <= 60:
yaitu jika hasil persentase kurang dari atau sama dengan 60%, maka dikategorikan “Beban Ringan”.

6. Fungsi elif digunakan pada persentase <= 85:
yaitu jika persentase di atas 60% dan sampai dengan 85%, maka statusnya “Beban Sedang”.

7. Fungsi else:
yaitu jika persentase lebih dari 85%, maka dikategorikan “Beban Berat”.

8. print(...)
akan menampilkan hasil perhitungan persentase dan status beban kepada pengguna yaitu Persentase Pemakaian: 66.67% dengan Status Beban itu "Beban Sedang".

In [11]:
9.
## ♨️ Looping + List untuk Pemeriksaan Suhu Boiler

suhu_boiler = [92.5, 88.7, 95.1, 102.3, 97.8]
batas_peringatan = 100.0


for i, suhu in enumerate(suhu_boiler):
    nomor_titik = i + 1
    print(f"Titik {nomor_titik}: {suhu}°C", end="")
    if suhu > batas_peringatan:
        print(" -> **PERINGATAN: OVERHEATING!**")
    else:
        print()


Titik 1: 92.5°C
Titik 2: 88.7°C
Titik 3: 95.1°C
Titik 4: 102.3°C -> **PERINGATAN: OVERHEATING!**
Titik 5: 97.8°C


PENJELASAN : Program ini buat untuk menampilkan setiap nilai suhu, dan beri peringatan jika suhu di atas 100°, pada 5 titik di boiler. Masalah yang diselesaikan oleh kode Python pada nomor 9 adalah pemantauan kondisi operasi suatu sistem, dalam hal ini boiler, dengan fokus pada deteksi dini kondisi kritis atau abnormal (overheating).
Penjelasan perbarisnya :
1. suhu_boiler = [92.5, 88.7, 95.1, 102.3, 97.8] :list berisi data suhu dari 5 titik di boiler.
2. batas_peringatan = 100.0 : batas suhu aman pada boiler.
3. for i, suhu in enumerate(suhu_boiler): Memulai perulangan for. Fungsi enumerate() menghasilkan pasangan (tuple) yang terdiri dari indeks (i, dimulai dari 0) dan nilai (suhu) dari list suhu_boiler di setiap iterasi.
4. nomor_titik = i + 1 : Menghitung nomor unit yang sebenarnya. Karena indeks (i) dimulai dari 0, penambahan 1 membuat penomoran titik dimulai dari 1 (Titik 1, Titik 2, dst.), yang lebih intuitif bagi pengguna.
5. print(f"Titik {nomor_titik}: {suhu}°C", end="") : Mencetak informasi dasar (Nomor Titik dan Suhu). Argumen end="" sangat penting: ia mengganti karakter newline (baris baru) standar dengan string kosong, memastikan pesan peringatan (jika ada) akan dicetak pada baris yang sama.
6. if suhu > batas_peringatan : Memeriksa apakah nilai suhu saat ini (suhu) lebih besar dari nilai 100.0
7. print(" -> **PERINGATAN: OVERHEATING!**") : Dieksekusi hanya jika kondisi if benar. Mencetak pesan peringatan yang ditambahkan tepat setelah nilai suhu (karena adanya end="" sebelumnya).
8. else: : Bagian yang akan dieksekusi jika kondisi if (suhu > 100.0) salah (yaitu, suhu < 100.0)
9. print() : Dieksekusi hanya jika tidak ada peringatan. Fungsi print() tanpa argumen hanya mencetak karakter newline (baris baru), yang diperlukan untuk memisahkan output dari iterasi saat ini dengan output dari iterasi berikutnya

In [7]:
# Challenge Analisis Konsumsi Energi Listrik Rumah

def hitung_energi_listrik_digunakan(daya_watt, waktu_jam):
    return daya_watt * waktu_jam

def klasifikasi_beban_listrik(persentase):
    if persentase <= 60:
        return "Beban Ringan"
    elif persentase <= 85:
        return "Beban Sedang"
    else:
        return "Beban Berat"

def main():
    print("Analisis Konsumsi Energi Listrik Rumah \n")

    kapasitas_maksimum = float(input("Masukkan kapasitas maksimum listrik rumah (Watt): "))
    jumlah_alat_listrik = int(input("Masukkan jumlah alat listrik yang digunakan: "))

    total_energi = 0

    for i in range(1, jumlah_alat_listrik + 1):
        print(f"\nAlat {i}")
        daya = float(input("  Masukkan daya alat yang digunakan (Watt): "))
        waktu = float(input("  Masukkan lama pemakaian (jam): "))

        energi = hitung_energi_listrik_digunakan(daya, waktu)
        total_energi += energi
        print(f"  Energi yang digunakan alat ini adalah: {energi:.2f} Wh")

    persentase = (total_energi / (kapasitas_maksimum * 24)) * 100
    status = klasifikasi_beban_listrik(persentase)

    print("\n HASIL ANALISIS")
    print(f"Total energi yang anda gunakan: {total_energi:.2f} Wh")
    print(f"Persentase pemakaian listrik: {persentase:.2f}%")
    print(f"Status beban listrik: {status}")

    ulang = "y"
    while ulang.lower() == "y":
        if status == "Beban Berat":
            print("\n⚠️ Rekomendasi: Kurangi penggunaan alat berdaya listrik tinggi atau matikan apabila anda tidak mengggunakan.")
        elif status == "Beban Sedang":
            print("\nℹ️ Rekomendasi: Gunakan alat yang hemat energi untuk efisiensi yang lebih baik.")
        else:
            print("\n✅ Rekomendasi: Penggunaan listrik sudah efisien, pertahankan kebiasaan anda.")

        ulang = input("\nApakah anda mau melihat rekomendasi lagi? (y/n): ")

    print("\nProgram telah selesai. Terima kasih telah menggunakan sistem analisis energi!")
main()



Analisis Konsumsi Energi Listrik Rumah 

Masukkan kapasitas maksimum listrik rumah (Watt): 2200
Masukkan jumlah alat listrik yang digunakan: 6

Alat 1
  Masukkan daya alat yang digunakan (Watt): 500
  Masukkan lama pemakaian (jam): 24
  Energi yang digunakan alat ini adalah: 12000.00 Wh

Alat 2
  Masukkan daya alat yang digunakan (Watt): 30
  Masukkan lama pemakaian (jam): 12
  Energi yang digunakan alat ini adalah: 360.00 Wh

Alat 3
  Masukkan daya alat yang digunakan (Watt): 75
  Masukkan lama pemakaian (jam): 12
  Energi yang digunakan alat ini adalah: 900.00 Wh

Alat 4
  Masukkan daya alat yang digunakan (Watt): 200
  Masukkan lama pemakaian (jam): 3
  Energi yang digunakan alat ini adalah: 600.00 Wh

Alat 5
  Masukkan daya alat yang digunakan (Watt): 400
  Masukkan lama pemakaian (jam): 24
  Energi yang digunakan alat ini adalah: 9600.00 Wh

Alat 6
  Masukkan daya alat yang digunakan (Watt): 20
  Masukkan lama pemakaian (jam): 5
  Energi yang digunakan alat ini adalah: 100.00 Wh



**Penjelasan:**

1. Fungsi def hitung_energi_listrik_digunakan(daya_watt, waktu_jam):
yaitu mendefinisikan fungsi untuk menghitung energi listrik yang digunakan.
Rumus: Energi (Wh) = Daya (Watt) × Waktu (jam).
Fungsi ini mengembalikan nilai energi dalam satuan Watt-hour (Wh).

2. Fungsi def klasifikasi_beban_listrik(persentase):
yaitu mendefinisikan fungsi untuk menentukan kategori beban listrik berdasarkan persentase pemakaian, yaitu ada Beban Ringan, Beban Sedang, dan Beban Berat.

3. Kode kapasitas_maksimum = float(input(...)) dan jumlah_alat_listrik = int(input(...))
akan menerima input dari pengguna berupa kapasitas listrik maksimum rumah (dalam Watt) dan jumlah alat listrik yang digunakan.

4. Fungsi for i in range(1, jumlah_alat_listrik + 1):
yaitu digunakan untuk memproses setiap alat listrik satu per satu.
Di dalamnya pengguna diminta mengisi daya alat dan lama pemakaian (jam).

5. Pemakaian energi yaitu hitung_energi_listrik_digunakan(daya, waktu)
yang akan menghitung energi tiap alat dengan memanggil kode hitung_energi_listrik_digunakan().
Nilai energi tiap alat kemudian dijumlahkan ke dalam variabel total_energi.

6. Persentase = (total_energi / (kapasitas_maksimum * 24)) * 100
akan enghitung persentase pemakaian energi terhadap kapasitas maksimum rumah selama 24 jam.

7. Pada status beban yaitu klasifikasi_beban_listrik(persentase) yang akan menentukan status beban listrik (Ringan, Sedang, atau Berat) berdasarkan hasil perhitungan persentase.

8. Pada bagian output:
akan menampilkan hasil perhitungan total energi, persentase pemakaian, dan status beban.

9. Fungsi perulangan while (while ulang.lower() == "y":)
yaitu memberi kesempatan pengguna untuk melihat rekomendasi penggunaan listrik secara berulang.

10. print("\nProgram telah selesai...")
Setelah pengguna memilih untuk berhenti (jawaban “n”), program menampilkan pesan penutup dan selesai dijalankan.

